# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='category',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='CostCategory',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.DeleteModel(
            name='RevenueCategory',
        ),
    ]
